-- 도서시퀀스
DROP SEQUENCE BOOK_SEQ;
CREATE SEQUENCE BOOK_SEQ;

-- 회원시퀀스
DROP SEQUENCE USER_SEQ;
CREATE SEQUENCE USER_SEQ;

-- 대출시퀀스
DROP SEQUENCE RENT_SEQ;
CREATE SEQUENCE RENT_SEQ;

-- 예약시퀀스
DROP SEQUENCE RESERVE_SEQ;
CREATE SEQUENCE RESERVE_SEQ;

DROP TABLE TB_COM_CODE CASCADE CONSTRAINT;
CREATE TABLE TB_COM_CODE(
  COMM_TY_CD VARCHAR2(10),
  COMM_CD VARCHAR2(20),
  COMM_CD_NM VARCHAR2(30),

  CONSTRAINT TB_CODE_PK PRIMARY KEY(COMM_TY_CD, COMM_CD)
);

-- 전화번호
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0100', '01', '010');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0100', '02', '011');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0100', '03', '016');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0100', '04', '019');

--장르
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0101', 'N', '소설');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0101', 'H', '역사/문화');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0101', 'S', '과학');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0101', 'P', '정치/사회');

--회원정보
DROP TABLE TB_COM_USER CASCADE CONSTRAINT;
CREATE TABLE TB_COM_USER(
  USER_CODE VARCHAR2(20),			       -- 유저코드
  ID VARCHAR2(20), 					       -- 아이디
  PW VARCHAR2(20), 					       -- 패스워드
  EMAIL VARCHAR2(50),                      -- 이메일
  NAME VARCHAR2(20),                       -- 이름
  BIRTH VARCHAR2(20),                      -- 생일
  POST_NUM VARCHAR2(20),                   -- 우편번호
  PHONE_CD VARCHAR2(2),                    -- 전화번호앞자리 코드
  PHONE_NUM VARCHAR2(20),                  -- 전화번호뒷자리
  ADDRESS VARCHAR2(100),                   -- 주소
  ENT_DATE VARCHAR2(20),                   -- 회원가입일
  RENT_BOOK_CNT NUMBER(5) DEFAULT 0,       -- 대출책수
  RESERVE_BOOK_CNT NUMBER(5) DEFAULT 0,    -- 예약책수
  GRADE VARCHAR2(5) DEFAULT 'M',           -- 회원권한
  CONSTRAINT TB_COM_USER_PK PRIMARY KEY(USER_CODE)
);

INSERT INTO TB_COM_USER(USER_CODE, ID, PW, EMAIL, NAME, BIRTH, POST_NUM, PHONE_CD, PHONE_NUM, ADDRESS, ENT_DATE, GRADE) VALUES (
					'USER0000' || USER_SEQ.NEXTVAL, 'admin', 'admin', 'admin@naver.com', '관리자', '1988-09-13', '133-441',
					'01', '4412-6921', '서울시 강남구 역삼1동 도서관리타워', '2015-11-11', 'A');

INSERT INTO TB_COM_USER(USER_CODE, ID, PW, EMAIL, NAME, BIRTH, POST_NUM, PHONE_CD, PHONE_NUM, ADDRESS, ENT_DATE, GRADE) VALUES (
					'USER0000' || USER_SEQ.NEXTVAL, 'ranone', 'ranone', 'ranone@naver.com', '존레논', '1972-06-19', '151-241',
					'01', '8822-5318', '서울시 성동구 성수2동 롯데캐슬', '2015-11-21', 'M');

INSERT INTO TB_COM_USER(USER_CODE, ID, PW, EMAIL, NAME, BIRTH, POST_NUM, PHONE_CD, PHONE_NUM, ADDRESS, ENT_DATE, GRADE) VALUES (
					'USER0000' || USER_SEQ.NEXTVAL, 'love86n', 'love86n', 'love86n@naver.com', '헤더신', '1986-12-20', '391-756',
					'01', '0235-7912', '서울시 송파구 방이3동 유라상가', '2015-12-01', 'M');

commit;
DROP TABLE TB_BOOK CASCADE CONSTRAINT;
CREATE TABLE TB_BOOK(
  BOOK_CODE VARCHAR2(20),                  -- 도서코드
  BOOK_NAME VARCHAR2(50),                  -- 도서명
  BOOK_IMAGE VARCHAR2(70),                 -- 도서이미지
  BOOK_PUBLISH_DATE VARCHAR2(20),          -- 출간일
  BOOK_PUBLISHER VARCHAR2(50),      	   -- 출판사
  BOOK_AUTHOR VARCHAR2(100),               -- 저자
  BOOK_GENRE_CD VARCHAR2(20),              -- 장르코드
  BOOK_REG_DATE VARCHAR2(20),              -- 도서등록일

  CONSTRAINT TB_BOOK_PK PRIMARY KEY(BOOK_CODE)
);

INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('N00' || BOOK_SEQ.NEXTVAL, '나의라임오렌지나무' ,    		'lime.jpg',       			'2010-04-15',			'동녘', 	  			'J.M. 바스콘셀로스',   		  'N',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('N00' || BOOK_SEQ.NEXTVAL, '데미안'          , 		'demian.jpg', 				'2009-01-20',			'민음사', 	  		'헤르만 헤세',     			  'N',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('N00' || BOOK_SEQ.NEXTVAL, '젊은 베르테르의 슬픔',   		'verter.jpg', 				'1999-03-20',			'민음사', 	 		'요한 볼프강 폰 괴테',     	  'N',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('N00' || BOOK_SEQ.NEXTVAL, '앵무새 죽이기'    ,    		'die of mockingbird.jpg', 	'2015-06-30', 			'열린책들',   			'하퍼 리',    				  'N',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('N00' || BOOK_SEQ.NEXTVAL, '파수꾼'         ,    		'hunter.jpg',       		'2015-07-15', 			'열린책들',   			'하퍼 리',    				  'N',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('N00' || BOOK_SEQ.NEXTVAL, '어린왕자'        ,    		'youngprince.jpg',  		'2015-11-20', 			'솔페리',   			'앙투안 드 생텍쥐페리',    	  'N',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('N00' || BOOK_SEQ.NEXTVAL, '악의숲'  ,           		'foretdesmanes.jpg',    	'2015-10-12',			'포레랑제',  			'장 크리스토프 그랑제',   	  'N',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('N00' || BOOK_SEQ.NEXTVAL, '센트럴파크'  ,        		'centralpark.jpg',      	'2014-12-11',			'밝은세상',   			'기욤 뮈소',   			  'N',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('N00' || BOOK_SEQ.NEXTVAL, '가면산장 살인사건'  ,   		'maskmurder.jpg',      		'2014-09-26', 			'재인',      			'히가시노 게이고',    		  'N',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('N00' || BOOK_SEQ.NEXTVAL, '갈매기의꿈'  ,       		'dreamofbird.jpg',       	'2015-10-30', 			'현문미디어', 			'리처드 바크',    			  'N',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('N00' || BOOK_SEQ.NEXTVAL, '허즈번드시크릿'  ,    		'husbandsecret.jpg',     	'2015-03-20', 			'마시멜로',   			'리안 모리아티',    		  'N',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('N00' || BOOK_SEQ.NEXTVAL, '걸 온 더 트레인'  ,    		'girlonthetrain.jpg',  		'2015-08-01', 			'북폴리오',   			'폴라 호킨스',    			  'N',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));

INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('H00' || BOOK_SEQ.NEXTVAL, '유신' ,   		 			'yusin.jpg',				'2010-04-15',			'한겨레출판사',			'한홍구', 				  'H', 			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('H00' || BOOK_SEQ.NEXTVAL, '해방후3년',		 			'haebang.jpg',				'2009-01-20', 			'생각정원', 	  		'조한성', 				  'H', 			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('H00' || BOOK_SEQ.NEXTVAL, '제주4.3을 묻는 너에게 슬픔',    'jeju4.3.jpg',	 			'1999-03-20', 			'서해문집',  			'허영선', 				  'H',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('H00' || BOOK_SEQ.NEXTVAL, '역사와책임'    ,  			'historyAndBlame.jpg', 		'2015-06-30', 			'한겨레출판사',  		'한홍구', 				  'H',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('H00' || BOOK_SEQ.NEXTVAL, '나의한국현대사'     , 		'mykoreanhistory.jpg',		'2015-07-15', 			'돌베개', 			'유시민', 				  'H',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('H00' || BOOK_SEQ.NEXTVAL, '민중을기록하라'     , 		'recordapeople.jpg',		'2015-11-20', 			'실천문학사', 			'박태순',					  'H',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('H00' || BOOK_SEQ.NEXTVAL, '임시정부의 품 안에서',       	'tempgo.jpg',				'2015-10-12', 			'푸른역사',	 		'김자동',     			  'H',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('H00' || BOOK_SEQ.NEXTVAL, '대한민국은 왜?',      		'whyKorea.jpg',				'2014-12-11', 			'사계절',	 			'김동춘',     			  'H',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('H00' || BOOK_SEQ.NEXTVAL, '유라시아역사기행건',  		    'yurasia.jpg',				'2014-09-26', 			'민음사',     		'강인욱',     			  'H',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('H00' || BOOK_SEQ.NEXTVAL, '오래된 서울',      			'oldSeoul.jpg',				'2015-10-30', 			'동하', 				'최종현',     			  'H',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('H00' || BOOK_SEQ.NEXTVAL, '근대조선과일본'  ,    		'koreaandjapan.jpg',		'2015-03-20',			'열린책들',			'조경달',     			  'H',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('H00' || BOOK_SEQ.NEXTVAL, '처음읽는 부여사인',  			'buyuhistory.jpg',			'2015-08-01', 			'사계절',   			'송호정',     			  'H',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));

INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('S00' || BOOK_SEQ.NEXTVAL, '인류의기원',				'originofpeople.jpg',		'2010-04-15',			'한겨레출판사',			'이상희', 				  'S', 			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('S00' || BOOK_SEQ.NEXTVAL, '도형이 쉬워지는 인도 베다수학',	'fastcalculate.jpg',		'2009-01-20', 			'생각정원', 	  		'마키노 다케후미', 			  'S', 			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('S00' || BOOK_SEQ.NEXTVAL, '세상의 모든 공식',    		'kongsik.jpg',				'1999-03-20', 			'서해문집',  			'존 M. 헨쇼', 			      'S',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('S00' || BOOK_SEQ.NEXTVAL, '아인슈타인이 말합니다',			'sayEin.jpg',				'2015-06-30', 			'한겨레출판사',  		'알베르트 아인슈타인', 		  'S',		 	 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('S00' || BOOK_SEQ.NEXTVAL, '세상물정의 물리학',			'physics.jpg',				'2015-07-15', 			'돌베개', 			'김범준',					  'S',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('S00' || BOOK_SEQ.NEXTVAL, '곤충연대기',				'bugslife.jpg',				'2015-11-20', 			'실천문학사', 			'스콧 R. 쇼',				  'S',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('S00' || BOOK_SEQ.NEXTVAL, '이기적유전자',	    		'selfishDNA.jpg',			'2015-10-12', 			'푸른역사',	 		'리처드 도킨스',			  'S',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));

INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('P00' || BOOK_SEQ.NEXTVAL, '21세기자본',				'21s.jpg',					'2015-06-30', 			'글항아리',			'토마 피케티 ', 			  'P',		 	 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('P00' || BOOK_SEQ.NEXTVAL, '왜 세계의 절반은 굶주리는가',		'whyhungry.jpg',			'2015-07-15', 			'갈라파고스',			'장 지글러',		 		  'P',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('P00' || BOOK_SEQ.NEXTVAL, '공정무역의 힘',				'fairtrade.jpg',			'2015-11-20', 			'시대의창',			'장 지글러',			  	  'P',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
INSERT INTO TB_BOOK(BOOK_CODE, BOOK_NAME, BOOK_IMAGE, BOOK_PUBLISH_DATE, BOOK_PUBLISHER, BOOK_AUTHOR, BOOK_GENRE_CD, BOOK_REG_DATE) VALUES('P00' || BOOK_SEQ.NEXTVAL, '윤리적소비',				'ethicalCost.jpg',			'2015-10-12', 			'메디치미디어',			'박지희',  				  'P',			 TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'));
COMMIT;

DROP TABLE TB_RENT CASCADE CONSTRAINT;
CREATE TABLE TB_RENT(
  RENT_NO VARCHAR2(30),                   -- 대출번호
  USER_CODE VARCHAR2(20),                 -- 유저코드
  BOOK_CODE VARCHAR2(20),                 -- 도서코드
  RENTAL_STATUS VARCHAR2(2) DEFAULT '0',  -- 대출상태       0:대출신청, 1:대출승인
  RENT_STA_DATE VARCHAR2(20),             -- 대출시작일
  RENT_END_DATE VARCHAR2(20),             -- 반납예정일
  EXTEND_YN	VARCHAR2(2) DEFAULT 'N',	  -- 연장유무
  CONSTRAINT TB_RENT_PK PRIMARY KEY(RENT_NO),
  CONSTRAINT TB_RENT_FK_USER FOREIGN KEY(USER_CODE) REFERENCES TB_COM_USER(USER_CODE),
  CONSTRAINT TB_RENT_FK_BOOK FOREIGN KEY(BOOK_CODE) REFERENCES TB_BOOK(BOOK_CODE)
);

DROP TABLE TB_RESERVE CASCADE CONSTRAINT;
CREATE TABLE TB_RESERVE(
  RESERVE_NO VARCHAR2(30),                -- 예약번호
  RENT_NO VARCHAR2(30),                   -- 대출번호
  USER_CODE VARCHAR2(20),                 -- 유저코드
  BOOK_CODE VARCHAR2(20),  				  -- 도서코드
  CONSTRAINT TB_RESERVE_PK PRIMARY KEY(RESERVE_NO),
  CONSTRAINT TB_RESERVE_FK_USER FOREIGN KEY(USER_CODE) REFERENCES TB_COM_USER(USER_CODE)
);


DROP TABLE TB_POST CASCADE CONSTRAINT;
CREATE TABLE TB_POST(
ZIPCODE VARCHAR2(10)
,SIDO VARCHAR2(50)
,GUGUN VARCHAR2(100)
,DONG VARCHAR2(100)
,BUNJI VARCHAR2(50)
,SEQ NUMBER PRIMARY KEY
);




DROP TABLE TB_COM_SEQ CASCADE CONSTRAINT;
CREATE TABLE TB_COM_SEQ(
  RENT_CODE VARCHAR2(10),
  RENT_NO VARCHAR2(20),

  CONSTRAINT TB_COM_SEQ_PK PRIMARY KEY(RENT_CODE)
);

commit;